### ISSUE TITLE
Arkserver Hilfe benötigt (LGSM)

### ISSUE THREAD

**Issue by TXAffeToto** [TXAffeToto/ArkserverHelp#1]
Ich brauche hilfe beim aufsetzten meines Arkservers über LGSM. beim validieren sprich ./arkserver validate kommt folgender fehler bzw. wird folgendes ausgegeben  : 

[ INFO ] Validate arkserver: Validating files: SteamCMD
* Validating may overwrite some customised files.
* https://docs.linuxgsm.com/commands/validate
Redirecting stderr to '/home/arkserver1/.steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...CreateBoundSocket: ::bind couldn't find an open port between 27060 and 27060
Failed to init SDL priority manager: SDL not found
Failed to set thread priority: per-thread setup failed
Failed to set thread priority: per-thread setup failed
OK.

Connecting anonymously to Steam Public...Couldn't bind to broadcast port 27036
Logged in OK
Waiting for user info...OK
Success! App '376030' already up to date.
[  OK  ] Validate arkserver: Validating files:

Ich denke dies ist weil bei /arkserver details unter Masterserver false steht allerdings weis ich nicht ,wie ich diesees problem lösen sollte

**Comment by bryan-ente** [comment]
1. Steam konnte sich nicht verbinden zwischen den angegebenen Ports.
Sind die Ports geöffnet? Überprüfen kannst du das hiermit: https://www.yougetsignal.com/tools/open-ports/

2. SDL wurde außerdem auch nicht gefunden.
-> Code kannste hier downloaden: https://wiki.libsdl.org/FrontPage

Hoffe diese total unnötige und verspätete Antwort hilft, falls du überhaupt noch den Server hast :]
